CHANGELOG.md, src/Crawler.php, src/Io.php, src/Output.php, src/Steps/Group.php, src/Steps/Loop.php, src/Steps/Step.php, src/Steps/StepInterface.php, tests/CrawlerTest.php, tests/IoTest.php, tests/OutputTest.php, tests/Pest.php, tests/Steps/GroupTest.php, tests/Steps/LoopTest.php, tests/Steps/StepTest.php
Add `uniqueOutputs()` method to Steps to get only unique output values.
When outputs are array or object, you can provide a key that will be used as identifier to check for uniqueness. Otherwise the arrays or objects will be serialized for comparison which will probably be slower.
=> Unique step outputs

CHANGELOG.md, src/Steps/AddsDataToResult.php, src/Steps/BaseStep.php, src/Steps/Group.php, src/Steps/Step.php, src/Steps/StepInterface.php, tests/Steps/GroupTest.php, tests/Steps/StepTest.php
Both methods work for Groups only when combineToSingleOutput is used (and was called before), otherwise they'll throw an Exception.
setResultKey, will add the whole combined output as value with the defined key. addKeysToResult adds keys from the combined output to the result.
Also change how the first param of addStep() works in groups: when its a string, don't set the result key, but use it as key in the combined output.
=> Implement Group setResultKey and addKeysToResult

CHANGELOG.md, src/Crawler.php, src/Steps/BaseStep.php, src/Steps/Group.php, src/Steps/Loop.php, src/Steps/Step.php, src/Steps/StepInterface.php, tests/CrawlerTest.php, tests/Steps/GroupTest.php, tests/Steps/LoopTest.php, tests/Steps/StepTest.php
Previously the use of Generators actually didn't make a lot of sense,
because the outputs of one step were only iterated and passed on to the
next step, after the current step was invoked with all its inputs. That
makes steps with a lot of inputs bottlenecks and causes bigger memory
consumption. So, change the crawler to immediately pass on outputs of
one step to the next step if there is one.
Also simplify how unique step output works. The crawler class doesn't
need to know if a step should produce unique output and handle it,
instead the step saves the unique keys in a class property until it is
reset by the Crawler (after a full run).
This also makes unique output from loops a lot simpler, which now also
works without cascadeWhenFinished.
=> Fix Generators usage

CHANGELOG.md, src/Crawler.php, tests/CrawlerTest.php
By calling `monitorMemoryUsage()` you can tell the Crawler to add log
messages with the current memory usage after every step invocation.
You can also set a limit in bytes when to start monitoring and below the
limit it won't log memory usage.
=> Log memory usage

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Filters/Filter.php, src/Steps/Filters/FilterInterface.php, src/Steps/Loop.php, src/Steps/StepInterface.php, tests/Steps/BaseStepTest.php, tests/Steps/CsvTest.php
Wasn't happy with the method naming filter() especially as there is also the need to concatenate filters with OR instead of AND. As where and orWhere are pretty common, this is it now.
=> Rename filter() to where() and add orWhere()

CHANGELOG.md, src/Steps/Csv.php, tests/Steps/CsvTest.php
The `Csv` step can now also be used without defining a column mapping. In that case it will use the values from the first line (so this makes sense when there are column headlines) as output array keys.
=> CSV auto mapping with column headlines

CHANGELOG.md, src/Steps/Html/GetLink.php, src/Steps/Html/GetLinks.php, tests/Steps/Html/GetLinkTest.php, tests/Steps/Html/GetLinksTest.php
The `GetLink` and `GetLinks` steps now have methods `onSameDomain()`, `notOnSameDomain()`, `onDomain()`, `onSameHost()`, `notOnSameHost()`, `onHost()` to restrict the which links to find.
=> Get links steps domain and host constraints

CHANGELOG.md, README.md, src/Crawler.php, src/Stores/SimpleCsvFileStore.php, src/Stores/Store.php, src/Stores/StoreInterface.php, tests/CrawlerTest.php
Automatically add the crawler's logger to the `Store` so you can also log messages from there. This can be breaking as the `StoreInterface` now also requires the `addLogger` method. The new abstract `Store` class already implements it, so you can just extend it.
Also prepare for v0.4 release tag.
=> Add logger to the store

CHANGELOG.md, src/Steps/Step.php, tests/Steps/StepTest.php
With the `maxOutputs()` method of the abstract `Step` class you can now limit how many outputs a certain step should yield at max. That's for example helpful during development, when you want to run the crawler only with a small subset of the data/requests it will actually have to process when you eventually remove the limits. When a step has reached its limit, it won't even call the `invoke()` method any longer until the step is reset after a run.
=> Limit outputs a step will yield at max

CHANGELOG.md, src/Crawler.php, tests/CrawlerTest.php
You can add a closure that'll receive all outputs cascaded within the Crawler. Should be mainly for debugging reasons.
=> Crawler output hooks

CHANGELOG.md, composer.json, src/Steps/Html.php, tests/Loader/Http/Cookies/CookieTest.php, tests/Steps/HtmlTest.php
As the selector is optional for the GetLink and GetLinks steps, also make the argument optional in the static methods.
=> Change getLink(s) argument to optional

phpstan.neon
- there is no need for treatPhpDocTypesAsCertain
- complete ignore regexp
=> Improve PHPStan config

src/Steps/Html/GetLink.php
```
if (error) unhappy path;
happy path;
```
The reverse is mind-twisting to read. It looks like the unhappy path is the desired one.
=> Switch order of happy path and unhappy path in GetLink

CHANGELOG.md, src/Steps/Dom.php, src/Steps/Html/DomQuery.php, src/Steps/Html/DomQueryInterface.php, tests/Steps/DomTest.php, tests/Steps/Html/CssSelectorTest.php, tests/Steps/Html/XPathQueryTest.php, tests/Steps/HtmlTest.php, tests/Steps/XmlTest.php
The `extract()` method of the `Html` and `Xml` (children of `Dom`) steps now also works with a single selector instead of an array with a mapping. Sometimes you'll want to just get a simple string output e.g. for a next step, instead of an array with mapped extracted data.
When a `DomQuery` (CSS selector or XPath query) doesn't match anything, its `apply()` method now returns `null` (instead of an empty string). When the `Html(/Xml)::extract()` method is used with a single, not matching selector/query, nothing is yielded. When it's used with an array with a mapping, it yields an array with null values. If the selector for one of the methods `Html(/Xml)::each()`, `Html(/Xml)::first()` or `Html(/Xml)::last()` doesn't match anything, that's not causing an error any longer, it just won't …
=> Make Dom::extract() work with single selector and fix behavior when selectors don't match

CHANGELOG.md, src/Steps/Loop.php, tests/Steps/LoopTest.php
Remove the (unnecessary) second argument from the `Loop::withInput()` method because when `keepLoopingWithoutOutput()` is called and `withInput()` is called after that call, it resets the behavior.
=> Remove second argument from Loop::withInput()

CHANGELOG.md, src/Loader/Http/Traits/WaitPolitely.php, src/Steps/Dom.php, src/Steps/Html/GetLink.php, src/Steps/Html/GetLinks.php, src/Stores/SimpleCsvFileStore.php, tests/Loader/Http/Cookies/CookieTest.php
When processing large amounts of data, some info messages that aren't really important can bloat the logs. Just remove them.
=> Reduce log messages

CHANGELOG.md, src/Loader/Http/Cookies/Date.php, tests/Loader/Http/Cookies/DateTest.php
When a server returns an expires date without dashes, it should still work.
=> Fix wrong cookie expires date format issue

CHANGELOG.md, src/Crawler.php, src/Io.php, tests/CrawlerTest.php, tests/IoTest.php
When result is not explicitly composed, but the outputs of the last step are arrays with string keys, it sets those keys on the Result object instead of setting a key `unnamed` with the whole array as value.
=> Improve default results from last step outputs

CHANGELOG.md, src/Steps/Dom.php, src/Steps/Html/DomQuery.php, src/Steps/Html/DomQueryInterface.php, tests/Steps/DomTest.php, tests/Steps/Html/CssSelectorTest.php, tests/Steps/Html/XPathQueryTest.php
In order to be able to also get absolute links when using the `extract()` method of Dom steps, the abstract `DomQuery` class now has a method `toAbsoluteUrl()`. The Dom step will automatically provide the `DomQuery` instance with the base url, presumed that the input was an instance of the `RespondedRequest` class and resolve the selected value against that base url.
=> Get absolute links when extracting data

.github/workflows/ci.yml, .github/workflows/install-chrome.sh, CHANGELOG.md, composer.json, src/Loader/Http/HttpLoader.php, src/Loader/Loader.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/JsGeneratedContent.php, tests/_Integration/_Server/PrintCookie.php, tests/_Integration/_Server/PrintHeaders.php, tests/_Integration/_Server/SetCookie.php
Add chrome-php/chrome composer dependency and simple option to use a headless chrome browser with the HttpLoader. So this is enough to get HTML after executing javascript in the browser. For more sophisticated tasks better not extend the HttpLoader further, but instead maybe create a separate Loader and/or Steps.
=> Add option to use headless browser with HttpLoader

CHANGELOG.md, src/Stores/SimpleCsvFileStore.php, tests/Stores/SimpleCsvFileStoreTest.php
If a result property value is an array it just prints them concatenated with ` | ` in the generated CSV file.
=> Improve SimpleCsvFileStore for nested results

CHANGELOG.md, composer.json, phpunit.xml, src/Loader/Http/HttpLoader.php, src/Steps/Loading/Http.php, src/Steps/Loading/HttpCrawl.php, tests/_Integration/Http/CrawlingTest.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/Crawling.php
It's for classic crawling all pages of a website. By default it follows all links on the same host, optionally all on same domain, including subdomains. You can start with any HTML document or optionally with one or more sitemaps. You can tell it to only load pages to a certain depth. You can filter URLs to load, by the path or even check the link element where it was found to decide if it should follow. You can also decide to load all pages, but yield only the responses matching your criteria (path, link element, custom URL check) to the next step. Besides that, improve the onError callback in the HttpLoader, fix a forgotten namespace in a test file and update the url and robots-txt package dependencies.
=> Add new HTTP::crawl() step

CHANGELOG.md, src/Steps/Html/DomQuery.php, src/Steps/Html/GetLink.php, src/Steps/Html/GetLinks.php, tests/Steps/Html/CssSelectorTest.php, tests/Steps/Html/GetLinkTest.php, tests/Steps/Html/GetLinksTest.php, tests/Steps/Html/XPathQueryTest.php
Getting absolute links via the `GetLink` and `GetLinks` steps and the `toAbsoluteUrl()` method of the `CssSelector` and `XPathQuery` classes, now also look for `<base>` tags in HTML when resolving the URLs.
=> Check HTML <base> tag when resolving URLs

CHANGELOG.md, src/Steps/Html.php, src/Steps/Html/MetaData.php, tests/Steps/Html/MetaDataTest.php
New step `Html::metaData()` to get data from meta tags (and title tag) in HTML documents.
=> New step to get Metadata from HTML

CHANGELOG.md, src/Steps/Html.php, src/Steps/Html/SchemaOrg.php, tests/CrawlerTest.php, tests/Loader/Http/HttpLoaderTest.php, tests/Steps/Html/SchemaOrgTest.php
New step `Html::schemaOrg()` (`SchemaOrg`) to get schema.org structured data in JSON-LD format from HTML documents.
Also fix a few minor things in existing tests.
=> New schema.org step

CHANGELOG.md, src/Loader/Http/Cookies/CookieJar.php, src/Loader/Http/HttpLoader.php, src/Loader/Http/Politeness/Throttler.php, src/Loader/Http/Politeness/TooManyRequestsHandler.php, tests/Loader/Http/HttpLoaderTest.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Http/TooManyRequestsTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/TooManyRequests.php
In case of a 429 (Too Many Requests) response, the `HttpLoader` now automatically waits and retries. By default, it retries twice and waits 10 seconds for the first retry and a minute for the second one. In case the response also contains a `Retry-After` header with a value in seconds, it complies to that. Exception: by default it waits at max `60` seconds (you can set your own limit if you want), if the `Retry-After` value is higher, it will stop crawling. If all the retries also receive a `429` it also throws an Exception and therefor stops crawling.
Besides that also fixed handling cookies for localhost or other hosts without a registrable domain name. And also removed the logger from the Throttler, as it doesn't log anything.
=> Handling 429 - Too Many Requests

CHANGELOG.md, src/Steps/Loading/Http.php, tests/Steps/Loading/HttpTest.php, tests/_Integration/Http/ErrorResponsesTest.php, tests/_Integration/Server.php
New methods `stopOnErrorResponse()` and `yieldErrorResponses()` that can be used with `Http` steps. By calling `stopOnErrorResponse()` the step will throw a `LoadingException` when a response has a 4xx or 5xx status code. By calling the `yieldErrorResponse()` even error responses will be yielded and passed on to the next steps.
The latter actually was the default behavior until now, but I think most people would either like to just ignore error responses or the whole crawler to fail/stop, so I changed this.
=> Controll what to do in case of error responses

src/Stores/JsonFileStore.php, tests/Stores/JsonFileStoreTest.php, tests/Stores/SimpleCsvFileStoreTest.php
I found your great project during #hacktoberfest and gave it a spin. I noticed that there is currently only an option for saving results as CSV and thought having the option for saving to a JSON file would be a nice addition to your project.
Usage is fairly simple, instead of adding the CSV Store to your crawler just add the new store instead:
`$crawler->setStore(new JsonFileStore(YOUR_STORE_PATH));`
=> Add JsonFileStore feature

CHANGELOG.md, src/Steps/Loading/Http.php, src/Steps/Loading/Http/Paginate.php, src/Steps/Loading/Http/Paginator.php, src/Steps/Loading/Http/PaginatorInterface.php, src/Steps/Loading/Http/Paginators/AbstractPaginator.php, src/Steps/Loading/Http/Paginators/SimpleWebsitePaginator.php, src/Steps/Loading/HttpCrawl.php, tests/Steps/Loading/GetSitemapsFromRobotsTxtTest.php, tests/Steps/Loading/Http/Paginators/SimpleWebsitePaginatorTest.php, tests/_Integration/Http/PaginationTest.php
There is the new `Paginate` child class of the `Http` step class (easy access via `Http::get()->paginate()`). It takes an instance of the `PaginatorInterface` and uses it to iterate through pagination links. There is one implementation of that interface, the `SimpleWebsitePaginator`. The `Http::get()->paginate()` method uses it by default, when called just with a CSS selector to get pagination links. Paginators receive all loaded pages and implement the logic to find pagination links. The paginator class is also called before sending a request, with the request object that is about to be sent as an argument (`prepareRequest()`). This way, it should even be doable to implement more complex pagination functionality. For example when pagination is built using POST request with query strings …
=> New functionality to paginate

CHANGELOG.md, src/HttpCrawler.php, src/Loader/Http/HttpLoader.php, tests/_Integration/Http/TimeoutTest.php, tests/_Integration/Http/TooManyRequestsTest.php, tests/_Integration/Server.php
The default values are 10 seconds for connect_timeout and 60 seconds for timeout. Also add the option to provide config options for the default guzzle client created inside the `HttpLoader`.
Further, removed the `httpClient()` method in the `HttpCrawler` class. If you want to provide your own HTTP client, implement a custom `loader` method passing your client to the `HttpLoader` instead.
=> Add default timeouts for the default guzzle client

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HttpLoaderTest.php
* New method `retryCachedErrorResponses()` in `HttpLoader`. When called, the loader will only use successful responses (status code < 400) from the cache and therefore retry already cached error responses.
* New method `writeOnlyCache()` in `HttpLoader` to only write to, but don't read from the response cache. Can be used to renew cached responses.
=> Improve response cache

CHANGELOG.md, src/Steps/Sitemap/GetUrlsFromSitemap.php, tests/Steps/Sitemap/GetUrlsFromSitemapTest.php
It now also works when the urlset tag contains attributes that would cause the symfony DomCrawler to not find any elements.
=> Improve the Sitemap::getUrlsFromSitemap() step

CHANGELOG.md, src/Loader/Http/HttpLoader.php
Fixed possibility of infinite redirects in `HttpLoader` by adding a redirects limit of 10.
=> Add max redirects limit

CHANGELOG.md, src/Steps/Step.php, tests/Steps/StepTest.php
The `validateAndSanitize...()` methods in the abstract `Step` class, when called with an array with one single element, automatically try to use that array element as input value.
=> Minor validation methods improvement

src/Steps/BaseStep.php, src/Steps/Group.php, src/Steps/Loop.php, src/Steps/Step.php, tests/Steps/GroupTest.php, tests/Steps/StepTest.php
When a new Io object is created it does always keep the addLaterToResult object from its parent.
=> Fix losing result data to add later

src/Steps/Json.php, tests/Steps/JsonTest.php
PHPs json_decode() can't decode JSON objects with keys that aren't wrapped in quotes. If json_decode() fails on the input string, it tries to find keys without quotes and add them.
=> Fix JSON object keys without quotes

CHANGELOG.md, src/Crawler.php, src/Steps/Loop.php
Probably the only use case is iterating over paginated list pages, which can be done using the new Paginator functionality. It will be removed in v1.0.
=> Deprecate the loop feature

src/Steps/Group.php, src/Steps/Step.php, tests/Steps/GroupTest.php, tests/Steps/StepTest.php
When using the new keepInputData() method in combination with useInputKey(), it still uses the full original input and not only the one key defined in useInputKey(), to add to the output.
=> Keeping input data uses original input

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Loading/Http.php, tests/Steps/Loading/HttpTest.php, tests/Steps/StepTest.php
* `addToResult()` now also works with serializable objects.
* If you know certain keys that the output of a step will contain, you can now also define aliases for those keys, to be used with `addToResult()`. The output of an `Http` step (`RespondedRequest`) contains the keys `requestUri` and `effectiveUri`. The aliases `url` and `uri` refer to `effectiveUri`, so `addToResult(['url'])` will add the `effectiveUri` as `url` to the result object.
=> Output key aliases for addToResult()

CHANGELOG.md, src/Steps/Loading/HttpCrawl.php, tests/_Integration/Http/CrawlingTest.php
Although the `HttpCrawl` step (`Http::crawl()`) already respected the limit of outputs defined via the `maxOutputs()` method, it actually didn't stop loading pages. The limit had no effect on loading, only on passing on outputs (responses) to the next step. Fixed it.
=> Http::crawl() step respect maxOutputs limit

CHANGELOG.md, src/Loader/Http/HttpLoader.php, src/Steps/Loading/Http.php, tests/Pest.php, tests/Steps/Loading/HttpTest.php, tests/_Integration/Http/RequestParamsFromInputTest.php
Add new methods `useInputKeyAsUrl()`, `useInputKeyAsBody()`, `useInputKeyAsHeader()` and `useInputKeyAsHeaders()` to the Http steps, so you can have dynamic body or headers coming from outputs from previous steps.
Also fix a minor issue with sending headers with multiple values, that seems to happen somewhere in guzzle.
=> Get HTTP request parameters from input data

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Filters/Filter.php, tests/Steps/StepTest.php
You can now also use the output key aliases when filtering step outputs. You can even use keys that are only present in the serialized version of an output object.
=> Filter by output key aliases

composer.json, src/Steps/Html/SchemaOrg.php, src/Steps/Json.php
Extracted the fixJsonString() method to a separate utils package, because it's also needed in the schema-org package. This new package shall be a place for all the functionality that will be needed in multiple crwlr packages.
=> Use new crwlr/utils Json class

CHANGELOG.md, src/Result.php, tests/ResultTest.php
When the current value of a result property is an associative array and we add another value, it makes the property value an array with that associative array as first element and add the second value.
=> Fix issue with array of arrays in result

CHANGELOG.md, src/Steps/Html/MetaData.php, tests/Steps/Html/MetaDataTest.php
Using the `only()` method of the `MetaData` (`Html::metaData()`) step class, the `title` property was always contained in the output, even if not listed in the `only` properties. This is fixed now.
=> Fix getting only certain HTML meta data properties

CHANGELOG.md, src/Steps/Json.php, tests/Steps/JsonTest.php
If the target of the "each" (like `Json::each('target', [...])`) does not exist in the input JSON data, the step yields nothing and logs a warning.
=> Improve Json step

CHANGELOG.md, src/Steps/Loading/HttpCrawl.php, src/Steps/Sitemap/GetUrlsFromSitemap.php, tests/_Integration/Http/CrawlingTest.php, tests/_Integration/_Server/Crawling.php
The `Http::crawl()` step now also work with sitemaps as input URL, where the `<urlset>` tag contains attributes that would cause the symfony DomCrawler to not find any elements.
=> Fix reading input sitemap in HTTP crawl step

CHANGELOG.md, src/Steps/Html/GetLink.php, src/Steps/Html/GetLinks.php, src/Steps/Loading/HttpCrawl.php, tests/Steps/Html/GetLinkTest.php, tests/Steps/Html/GetLinksTest.php, tests/_Integration/_Server/Crawling.php
The `Http::crawl()` step, as well as the `Html::getLink()` and `Html::getLinks()` steps now ignore links, when the `href` attribute starts with `mailto:`, `tel:` or `javascript:`.
=> Ignore special non HTTP links

CHANGELOG.md, src/Loader/Http/HttpLoader.php, src/Loader/Http/Politeness/Throttler.php, tests/Loader/Http/HttpLoaderPolitenessTest.php
Add missing calls to track request start and end times, so the call to `waitForGo()` actually works as expected.
=> Fix throttling when using the headless browser

CHANGELOG.md, src/Loader/Http/HttpLoader.php, src/Loader/Loader.php, tests/Loader/Http/HttpLoaderTest.php, tests/Loader/LoaderTest.php, tests/Steps/GroupTest.php
New `onCacheHit` hook in the `Loader` class (in addition to `beforeLoad`, `onSuccess`, `onError` and `afterLoad`) that is called in the `HttpLoader` class when a response for a request was found in the cache.
=> New onCacheHit Loader hook

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HttpLoaderTest.php
When a URL redirects, the `trackRequestEndFor()` method of the `HttpLoader`'s `Throttler` instance is called only once at the end and with the original request URL.
=> Fix tracking request end for redirected requests

CHANGELOG.md, src/Loader/Http/Exceptions/LoadingException.php, src/Loader/Http/HttpLoader.php, src/Loader/Http/ProxyManager.php, src/Loader/LoaderInterface.php, tests/Loader/Http/ProxyManagerTest.php, tests/Steps/Loading/Http/Paginators/SimpleWebsitePaginatorTest.php, tests/_Integration/Http/ProxyingTest.php, tests/_Integration/ProxyServer.php
Add new methods `HttpLoader::useProxy()` and
`HttpLoader::useRotatingProxies([...])` to define proxies that the loader shall use. They can be used with a guzzle HTTP client instance (default) and when the loader uses the headless chrome browser. Using them when providing some other PSR-18 implementation will throw an exception.
(see https://github.com/crwlrsoft/crawler/issues/99)
Also, fix the `HttpLoader::load()` implementation won't throw any exception, because it shouldn't kill a crawler run. When you want any loading error to end the whole crawler execution
`HttpLoader::loadOrFail()` should be used. Also adapted the phpdoc in the `LoaderInterface`.
=> Enable the use of Proxies

CHANGELOG.md, src/Steps/Html/CssSelector.php, src/Steps/Html/Exceptions/InvalidDomQueryException.php, src/Steps/Html/GetLink.php, src/Steps/Html/GetLinks.php, src/Steps/Html/XPathQuery.php, tests/Steps/Html/CssSelectorTest.php, tests/Steps/Html/XPathQueryTest.php
When creating a `CssSelector` or `XPathQuery` instance with invalid selector/query syntax, an `InvalidDomQueryException` is now immediately thrown. This change is considered to be not only non-breaking, but actually a fix, because the `CssSelector` would otherwise throw an exception later when the `apply()` method is called. The `XPathQuery` would silently return no result without notifying you of the invalid query and generate a PHP warning.
=> Validate CSS Selectors and XPath Queries earlier

CHANGELOG.md, src/Steps/Html/Exceptions/InvalidDomQueryException.php, tests/Steps/Html/Exceptions/InvalidDomQueryExceptionTest.php
Add forgotten getter method to get the DOM query that is attached to an `InvalidDomQueryException` instance.
=> Add forgotten getter method

CHANGELOG.md, src/Cache/FileCache.php, tests/Cache/FileCacheTest.php
When FileCache compression is activated, the FileCache assumed that all cache files that it will read are compressed. But there could be existing cache files created without compression activated which lead to errors. The FileCache now first checks if the content is compressed and only tries to decode if it is.
=> Fix reading uncompressed files

CHANGELOG.md, LICENSE, src/Steps/Loading/Http/Paginators/QueryParams/AbstractQueryParamManipulator.php, src/Steps/Loading/Http/Paginators/QueryParams/Decrementor.php, src/Steps/Loading/Http/Paginators/QueryParams/Incrementor.php, src/Steps/Loading/Http/Paginators/QueryParamsPaginator.php, tests/Steps/Loading/Http/Paginators/QueryParams/DecrementorTest.php, tests/Steps/Loading/Http/Paginators/QueryParams/IncrementorTest.php, tests/Steps/Loading/Http/Paginators/QueryParamsPaginatorTest.php
The `QueryParamsPaginator` can now also increase and decrease non first level query param values like `foo[bar][baz]=5` using dot notation: `QueryParamsPaginator::paramsInUrl()->increaseUsingDotNotation('foo.bar.baz', 5)`.
=> Enable manipulating nested query params

.php-cs-fixer.php, CHANGELOG.md, composer.json, src/Cache/CacheItem.php, src/Cache/FileCache.php, src/Loader/Http/Cookies/CookieJar.php, src/Loader/Http/HttpLoader.php, src/Loader/Http/Messages/RespondedRequest.php, src/Loader/Http/Politeness/RobotsTxtHandler.php, src/Loader/Http/Politeness/Throttler.php, src/Steps/Dom.php, src/Steps/Group.php, src/Steps/Html.php, src/Steps/Html/DomQuery.php, src/Steps/Html/GetLink.php, src/Steps/Html/SelectorTarget.php, src/Steps/Loading/GetSitemapsFromRobotsTxt.php, src/Steps/Loading/Http.php, src/Steps/Loading/Http/Paginator.php, src/Steps/Loading/Http/Paginators/SimpleWebsitePaginator.php, src/Steps/Loading/Http/Paginators/StopRules/IsEmptyInDom.php, src/Steps/Loading/HttpCrawl.php, src/Steps/Xml.php, tests/Steps/Html/CssSelectorTest.php, tests/_Integration/Http/CrawlingTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/Crawling.php
The `DomQuery` class (parent of `CssSelector` (`Dom::cssSelector`) and `XPathQuery` (`Dom::xPath`)) has a new method `formattedText()` that uses the new crwlr/html-2-text package to convert the HTML to formatted plain text. You can also provide a customized instance of the `Html2Text` class to the `formattedText()` method.
Also added a lot of missing throws doblock tags in the whole codebase and adapted PHP CS Fixer config a little.
=> New DomQuery::formattedText() method

CHANGELOG.md, composer.json, src/Loader/Http/HeadlessBrowserLoaderHelper.php, src/Loader/Http/HttpBaseLoader.php, src/Loader/Http/HttpLoader.php, src/Steps/Loading/Http.php, src/Steps/Loading/HttpBase.php, src/Steps/Step.php, tests/Loader/Http/HttpLoaderPolitenessTest.php, tests/_Integration/Http/ProxyingTest.php
For being more flexible to build a separate headless browser loader (in an extension package) extract the most basic HTTP loader functionality to a new `HttpBaseLoader` and important functionality for the headless browser loader to a new `HeadlessBrowserLoaderHelper`. It's considered a fix, because there's no new functionality, just refactoring existing code for better extendability.
Also add `--display-warnings` option to test commands.
=> HttpLoader Separation

CHANGELOG.md, src/Steps/Sitemap/GetUrlsFromSitemap.php, tests/Steps/Sitemap/GetUrlsFromSitemapTest.php
Fixes the regex for fixing the <urlset> tag, when XML content contains no linebreaks.
=> Fix issue in Sitemap::getUrlsFromSitemap()

CHANGELOG.md, src/Crawler.php, src/Loader/Http/Messages/RespondedRequest.php, src/Steps/BaseStep.php, tests/CrawlerTest.php, tests/Loader/Http/Messages/RespondedRequestTest.php, tests/Steps/StepTest.php
* Enable dot notation in `Step::addToResult()`, so you can get data from nested output, like: `$step->addToResult(['url' => 'response.url', 'status' => 'response.status', 'foo' => 'bar'])`.
* When a step adds output properties to the result, and the output contains objects, it tries to serialize those objects to arrays, by calling `__serialize()`. If you want an object to be serialized differently for that purpose, you can define a `toArrayForAddToResult()` method in that class. When that method exists, it's preferred to the `__serialize()` method.
* Implemented above-mentioned `toArrayForAddToResult()` method in the `RespondedRequest` class, so on every step that somehow yields a `RespondedRequest` object, you can use the keys `url`, `uri`, `status`, `headers` and `body` with the …
=> Enable adding to result from nested output

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HttpLoaderTest.php, tests/_Stubs/RespondedRequestChild.php
Make method `HttpLoader::addToCache()` public, so steps can update a cached response with an extended version.
=> Enable updating cached responses via the Loader

CHANGELOG.md, src/HttpCrawler.php, src/Loader/Http/HttpLoader.php, tests/CrawlerTest.php, tests/Loader/Http/HttpLoaderTest.php, tests/_Stubs/Crawlers/DummyOne.php, tests/_Stubs/Crawlers/DummyTwo.php, tests/_Stubs/Crawlers/DummyTwo/DummyTwoLoader.php, tests/_Stubs/Crawlers/DummyTwo/DummyTwoLogger.php, tests/_Stubs/Crawlers/DummyTwo/DummyTwoUserAgent.php
When using `HttpLoader::cacheOnlyWhereUrl()` and a request was redirected (maybe even multiple times), previously all URLs in the chain had to match the filter rule. As this isn't really practicable, now only one of the URLs has to match the rule.
=> Fix issue with cache filters and redirects

CHANGELOG.md, src/Steps/Json.php, tests/Steps/JsonTest.php, tests/_Integration/Http/RequestParamsFromInputTest.php
Allow getting the whole decoded JSON as array with the new `Json::all()` and also allow to get the whole decoded JSON, when using `Json::get()`, inside a mapping using either empty string or `*` as target. Example: `Json::get(['all' => '*'])`. `*` only works, when there is no key `*` in the decoded data.
Make it work with responses loaded by a headless browser. If decoding the input string fails, it now checks if it could be HTML. If that's the case, it extracts the text content of the `<body>` and tries to decode this instead.
=> JSON step improvement

.gitignore, CHANGELOG.md, src/Steps/Loading/HttpCrawl.php, tests/_Integration/Http/CrawlingTest.php
Fix a PHP error that happened when the loader returns `null` for the initial request in the `Http::crawl()` step.
=> Fix issue in Http::crawl() step

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Group.php, src/Steps/Step.php, tests/Steps/StepTest.php
When the `useInputKey()` method is used on a step and the defined key does not exist in input, it logs a warning and does not invoke the step instead of throwing an `Exception`.
=> Fail soft when input key is missing

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php, tests/Pest.php
New methods `HeadlessBrowserLoaderHelper::setTimeout()` and `HeadlessBrowserLoaderHelper::waitForNavigationEvent()` to allow defining the timeout for the headless chrome in milliseconds (default 30000 = 30 seconds) and the navigation event (`load` (default), `DOMContentLoaded`, `firstMeaningfulPaint`, `networkIdle`, etc.) to wait for when loading a URL.
=> Allow further headless chrome configuration

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php
So we're able to get the currently configured timeout value for the headless chrome browser.
=> Also add a getTimeout() function

.php-cs-fixer.php, CHANGELOG.md, src/Loader/Http/HttpLoader.php
Add `HttpLoader::browser()` as a replacement for
`HttpLoader::browserHelper()` and deprecate the `browserHelper()` method. It's an alias and just because it will read a little better: `$loader->browser()->xyz()` vs. `$loader->browserHelper()->xyz()`. `HttpLoader::browserHelper()` will be removed in v2.0.
Also deprecate `HttpLoader::setHeadlessBrowserOptions()`, `HttpLoader::addHeadlessBrowserOptions()` and
`HttpLoader::setChromeExecutable()`. Use
`$loader->browser()->setOptions()`, `$loader->browser()->addOptions()` and `$loader->browser()->setExecutable()` instead.
Further also try parallelisation in PHP CS Fixer.
=> Replace browserHelper() with browser()

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HttpLoaderTest.php
When using `HttpLoader::cacheOnlyWhereUrl()` to restrict caching, the filter rule is not only applied when adding newly loaded responses to the cache, but also for using cached responses. Example: a response for `https://www.example.com/foo` is already available in the cache, but `$loader->cacheOnlyWhereUrl(Filter::urlPathStartsWith('/bar/'))` was called, the cached response is not used.
=> Apply cache filter also for usage of cached responses

CHANGELOG.md, src/Steps/Loading/Http.php, tests/Steps/Loading/HttpTest.php
Prevent PHP warnings when an HTTP response includes a `Content-Type: application/x-gzip` header, but the content is not actually compressed. This issue also occurred with cached responses, because compressed content is decoded during caching. Upon retrieval from the cache, the header indicated compression, but the content was already decoded.
=> Prevent PHP warnings

CHANGELOG.md, src/HttpCrawler/AnonymousHttpCrawlerBuilder.php, src/UserAgents/UserAgent.php, tests/HttpCrawler/AnonymousHttpCrawlerBuilderTest.php
Static method `UserAgent::mozilla5CompatibleBrowser()` to get a `UserAgent` instance with the user agent string
`Mozilla/5.0 (compatible)` and also the new method `withMozilla5CompatibleUserAgent` in the `AnonymousHttpCrawlerBuilder` that you can use like this:
`HttpCrawler::make()->withMozilla5CompatibleUserAgent()`.
=> Mozilla 5.0 compatible user agent

CHANGELOG.md, composer.json, phpstan.neon, src/Steps/Loading/Http/Paginators/StopRules/Contains.php, src/Steps/Loading/Http/Paginators/StopRules/NotContains.php, src/Steps/Loading/Http/Paginators/StopRules/PaginatorStopRules.php, tests/Steps/Loading/Http/Paginators/StopRules/ContainsTest.php, tests/Steps/Loading/Http/Paginators/StopRules/NotContainsTest.php
Adds `PaginatorStopRules::contains()` and
`PaginatorStopRules::notContains()` causing the paginator to stop when a certain string is contained (or not) in the response body.
=> New paginator stop rules

CHANGELOG.md, src/Cache/CacheItem.php, src/Cache/FileCache.php, src/Logger/CliLogger.php, tests/Cache/FileCacheTest.php, tests/Pest.php, tests/_Stubs/DummyLogger.php
Add new methods `FileCache::prolong()` and `FileCache::prolongAll()` to allow prolonging the time to live for cached responses.
=> Cache ttl prolongation

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, src/Steps/Loading/Http/Browser/BrowserAction.php, src/Steps/Loading/HttpBase.php, tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/BrowserActions/ClickAndWaitForReload.php, tests/_Integration/_Server/BrowserActions/EvaluateAndWaitForReload.php, tests/_Integration/_Server/BrowserActions/EvaluateAndWaitForReloadReloaded.php, tests/_Integration/_Server/BrowserActions/Main.php, tests/_Integration/_Server/BrowserActions/Wait.php, tests/_Integration/_Server/SetCookieJs.php, tests/_Integration/_Server/SetDelayedCookieJs.php
Adds post browser navigate hooks that are passed from `Http` steps to the browser loader helper and are executed after the headless browser navigated to the specified URL. They are called with the chrome-php `Page` object as argument, so you can run things on that page before getting the HTML and returning the response.
=> Post Browser Navigate Hooks

CHANGELOG.md, src/Loader/Http/Cookies/CookieJar.php, src/Loader/Http/HeadlessBrowserLoaderHelper.php, src/Loader/Http/HttpLoader.php, src/Loader/Http/Politeness/Throttler.php, src/Loader/Loader.php, tests/Loader/Http/Cookies/CookieJarTest.php, tests/Loader/Http/HttpLoaderPolitenessTest.php, tests/Loader/Http/Politeness/ThrottlerTest.php, tests/Loader/LoaderTest.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/SetCookieJs.php, tests/_Integration/_Server/SetDelayedCookieJs.php
Also add cookies, set during headless browser usage, to the cookie jar. When switching back to the (guzzle) HTTP client the cookies should also be sent.
=> Add browser cookies to the cookie jar

src/Loader/Http/Cookies/CookieJar.php
Now you can clearly see what is going on in `buildSetCookieHeaderFromBrowserCookie`.
Review: https://github.com/crwlrsoft/crawler/blob/f0da585ee8798e49a837b02f741c398a9356259e/src/Loader/Http/Cookies/CookieJar.php#L124
=> Make buildSetCookieHeaderFromBrowserCookie robust

.github/workflows/ci.yml, CHANGELOG.md, src/Loader/Http/Cookies/CookieJar.php, src/Steps/Loading/HttpBase.php, src/Stores/SimpleCsvFileStore.php
Further also improve github actions workflow by merging the two test jobs and phpstan and cs fixer.
=> Minor improvements for PHP 8.4

.php-cs-fixer.php, composer.json
Because parallel execution was introduced with that version. Also seems that single_class_element_per_statement isn't necessary. It does not change anything when ran without it. And also add funding block to composer.json.
=> PHP CS Fixer min version 3.57

CHANGELOG.md, phpstan.neon, src/Steps/Dom.php, src/Steps/Dom/HtmlDocument.php, src/Steps/Dom/Node.php, src/Steps/Dom/XmlDocument.php, src/Steps/Html/CssSelector.php, src/Steps/Html/XPathQuery.php, tests/Steps/BaseStepTest.php, tests/Steps/Dom/HtmlDocumentTest.php, tests/Steps/Dom/HtmlElementTest.php, tests/Steps/Dom/NodeListTest.php, tests/Steps/Dom/NodeTest.php, tests/Steps/Loading/Http/DocumentTest.php, tests/Steps/Loading/Http/Paginators/StopRules/IsEmptyInJsonTest.php
I found that I was wrong about XPath not being available for usage with the new DOM API in PHP 8.4. As it is still available, remove the deprecations introduced in 3.0.0.
=> Undeprecate XPath Functionality

CHANGELOG.md, src/Steps/Html/DomQuery.php, tests/_Integration/Http/CharsetTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/NonUtf8.php
=> Fix non UTF-8 char issue

.gitignore, CHANGELOG.md, src/Steps/Html/CssSelector.php, src/Steps/Html/XPathQuery.php, tests/Steps/HtmlTest.php, tests/Steps/XmlTest.php
Minor improvement for the `DomQuery` (base for `Dom::cssSelector()` and `Dom::xPath()`): enable providing an empty string as selector, to simply get the node that the selector is applied to.
=> Empty DOM Queries

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/PageInitScript.php
* New method `HeadlessBrowserLoaderHelper::setPageInitScript()` (`$crawler->getLoader()->browser()->setPageInitScript()`) to provide javascript code that is executed on every new browser page before navigating anywhere.
* New method `HeadlessBrowserLoaderHelper::useNativeUserAgent()` (`$crawler->getLoader()->browser()->useNativeUserAgent()`) to allow using the native `User-Agent` that your Chrome browser sends by default.
=> Two new HeadlessBrowserLoaderHelper features

CHANGELOG.md, src/Steps/Step.php, tests/Steps/CsvTest.php, tests/Steps/DomTest.php, tests/Steps/Html/GetLinkTest.php, tests/Steps/Html/GetLinksTest.php, tests/Steps/Loading/HttpTest.php, tests/Steps/StepTest.php
When the `validateAndSanitize()` method of a step throws an `InvalidArgumentException`, the exception is now caught, logged and the step is not invoked with the invalid input. This improves fault tolerance. Feeding a step with one invalid input shouldn't cause the whole crawler run to fail. Exceptions other than
`InvalidArgumentException` remain uncaught.
=> Catch and log invalid step inputs

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/RssFeed.php
When loading a non-HTML document (e.g., XML) via the Chrome browser, the library now retrieves the original source. Previously, it returned the outerHTML of the rendered document, which wrapped the content in an HTML structure.
=> Fix getting non HTML documents via browser

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php, tests/_Integration/Http/HeadlessBrowserTest.php
`HttpLoader::dontUseCookies()` now also works when using the Chrome browser. Cookies are cleared before every request.
=> Fix HttpLoader::dontUseCookies() with browser

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/BrokenMimeTypeRss.php
Another improvement for getting XML source when using the browser, in cases where Chrome doesn't identify the response as an XML document (even though a Content-Type header is sent).
=> Get XML via chrome improvement

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Steps/Filters/ComparisonFilterTest.php, tests/Steps/Filters/Enums/ComparisonFilterRuleTest.php, tests/_Integration/Http/ErrorResponsesTest.php, tests/_Integration/Http/RobotsTxtTest.php, tests/_Integration/Server.php, tests/_Integration/_Server/HelloWorld.php
Warnings about loader hooks being called multiple times, when using a `BotUserAgent` and therefore loading and respecting the robots.txt file, or when using the `Http::stopOnErrorResponse()` method.
Also add some more tests for the greater than and less than comparison filters, when comparing values with different types.
=> Fix loader hooks warning with BotUserAgent

CHANGELOG.md, src/Steps/Html/DomQuery.php, tests/Steps/Html/CssSelectorTest.php, tests/Steps/Html/XPathQueryTest.php
Fix deprecation warning triggered in the `DomQuery` class, when trying to get the value of an HTML/XML attribute that does not exist on the element.
=> Fix getting value of non existing attribute

CHANGELOG.md, src/Loader/Http/HttpLoader.php, tests/Loader/Http/HttpLoaderTest.php, tests/Loader/Http/Politeness/RobotsTxtHandlerTest.php, tests/Pest.php, tests/Steps/Loading/HttpTest.php
Trying to load a relative reference URI (no scheme and host/authority, only path) via the `HttpLoader` now immediately logs (or throws when `loadOrFail()` is used) an error instead of trying to actually load it.
=> Prevent loading relative reference URI

CHANGELOG.md, src/Steps/Dom.php, tests/Steps/HtmlTest.php, tests/Steps/XmlTest.php
When a child step is nested in the `extract()` method of an `Html` or `Xml` step, and does not use `each()` as the base, the extracted value is an array with the keys defined in the `extract()` call, rather than an array of such arrays as it would be with `each()` as base.
=> Fix data structure of nested HTML/XML steps

CHANGELOG.md, src/Loader/Http/HeadlessBrowserLoaderHelper.php, src/Steps/Loading/Http/Browser/BrowserAction.php, tests/_Integration/Http/HeadlessBrowserTest.php, tests/_Integration/_Server/BrowserActions/ClickAndWaitForReload.php, tests/_Integration/_Server/BrowserActions/Main.php, tests/_Integration/_Server/BrowserActions/Wait.php
- Added new `BrowserAction`s for `postBrowserNavigateHook()`:
- `clickInsideShadowDom()`
- `moveMouseToElement()`
- `moveMouseToPosition()`
- `scrollDown()`
- `scrollUp()`
- `typeText()`
- `waitForReload()`
- Added `includeShadowElementsInHtml()` to `HeadlessBrowserLoaderHelper` to include shadow DOM content in returned HTML.
- Updated `clickElement()` to automatically wait for elements before clicking, removing the need for `waitUntilDocumentContainsElement()`.
- Deprecated `clickElementAndWaitForReload()` and `evaluateAndWaitForReload()`, recommending `clickElement()` or `evaluate()` with `waitForReload()` instead.
=> Improve post navigate hook browser actions

CHANGELOG.md, src/Steps/Loading/HttpBase.php, tests/Steps/Loading/HttpTest.php
Fixes an issue when using
`Http::get()->useBrowser()->postBrowserNavigateHook()`. Previously in this case, when the loader is configured to use the HTTP client, the post browser navigate hook was actually not set because of an issue with the order, things happened internally.
=> Fix order of calls in HttpBase step

CHANGELOG.md, src/Logger/PreStepInvocationLogger.php, src/Steps/BaseStep.php, src/Steps/Dom.php, tests/Loader/Http/HttpLoaderTest.php, tests/Logger/PreStepInvocationLoggerTest.php, tests/Steps/BaseStepTest.php, tests/Steps/DomTest.php, tests/_Integration/Http/HeadlessBrowserTest.php
When providing an empty base selector to an `Html` step (`Html::each('')`, `Html::first('')`, `Html::last('')`), it won't fail with an error, but instead log a warning, that it most likely doesn't make sense.
=> Fix empty base selectors with `Html` extract step

CHANGELOG.md, src/Steps/Group.php, tests/Steps/GroupTest.php
The `Step::keep()` methods now also work when applied to child steps within a group step.
=> Fix keeping data from group child steps

CHANGELOG.md, src/Steps/Step.php, tests/Steps/Dom/XmlDocumentTest.php, tests/Steps/Loading/HttpTest.php
When feeding an `Http` step with a string that is not a valid URL (e.g. `https://`), the exception when trying to parse it as a URL is caught, and an error logged.
=> Handle invalid URL input in Http steps

CHANGELOG.md, phpstan.neon, src/Steps/Dom/Node.php, src/Steps/Refiners/DateTime/DateTimeFormat.php, src/Steps/Refiners/DateTimeRefiner.php, src/Steps/Refiners/Html/RemoveFromHtml.php, src/Steps/Refiners/HtmlRefiner.php, tests/Steps/Dom/NodeTest.php, tests/Steps/Refiners/DateTime/DateTimeFormatTest.php, tests/Steps/Refiners/Html/RemoveFromHtmlTest.php
* `DateTimeRefiner::reformat('Y-m-d H:i:s')` to reformat a date time string to a different format. Tries to automatically recognize the input format. If this does not work, you can provide an input format to use as the second argument.
* `HtmlRefiner::remove('#foo')` to remove nodes matching the given selector from selected HTML.
=> Add new refiners

CHANGELOG.md, src/Steps/Step.php, tests/Pest.php, tests/Steps/StepTest.php
Steps that produce multiple outputs per input can now group them per input by calling the new `Step::oneOutputPerInput()` method.
=> Force one output per input

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Group.php, src/Steps/Loading/HttpBase.php, src/Steps/Step.php, src/Utils/TemplateString.php, tests/Steps/Loading/HttpTest.php, tests/Utils/TemplateStringTest.php
`Http` steps now have a new `staticUrl()` method, and you can also use variables within that static URL - as well as in request headers and in the body - like
`https://www.example.com/foo/[crwl:some_extracted_property]`. These variables will be replaced with the corresponding properties from input data (also works with kept data).
=> Use extracted data to dynamically build request URLs

CHANGELOG.md, src/Steps/BaseStep.php, src/Steps/Refiners/DateTime/DateTimeFormat.php, src/Steps/Refiners/Html/RemoveFromHtml.php, src/Steps/Refiners/String/AbstractStringRefiner.php, src/Steps/Refiners/String/StrAfterFirst.php, src/Steps/Refiners/String/StrAfterLast.php, src/Steps/Refiners/String/StrBeforeFirst.php, src/Steps/Refiners/String/StrBeforeLast.php, src/Steps/Refiners/String/StrBetweenFirst.php, src/Steps/Refiners/String/StrBetweenLast.php, src/Steps/Refiners/String/StrReplace.php, src/Steps/Refiners/Url/AbstractUrlRefiner.php, tests/Steps/BaseStepTest.php, tests/Steps/Refiners/DateTime/DateTimeFormatTest.php, tests/Steps/Refiners/Html/RemoveFromHtmlTest.php, tests/Steps/Refiners/String/AfterFirstTest.php, tests/Steps/Refiners/String/AfterLastTest.php, tests/Steps/Refiners/String/BeforeFirstTest.php, tests/Steps/Refiners/String/BeforeLastTest.php, tests/Steps/Refiners/String/BetweenFirstTest.php, tests/Steps/Refiners/String/BetweenLastTest.php, tests/Steps/Refiners/String/ReplaceTest.php, tests/Steps/Refiners/Url/WithFragmentTest.php, tests/Steps/Refiners/Url/WithHostTest.php, tests/Steps/Refiners/Url/WithPathTest.php, tests/Steps/Refiners/Url/WithPortTest.php, tests/Steps/Refiners/Url/WithQueryTest.php, tests/Steps/Refiners/Url/WithSchemeTest.php, tests/Steps/Refiners/Url/WithoutPortTest.php
* An issue that occurred, when a step uses the `PreStepInvocationLogger`. As refiners also use the logger, a newer logger (replacing the `PreStepInvocationLogger`) is now also passed to all registered refiners of a step.
* Enable applying refiners to output properties with array value. E.g. if a step outputs an array of URLs (`['https://...', 'https://...']`), a `UrlRefiner` will be applied to all those URLs.
=> Two fixes/improvements

CHANGELOG.md, src/Steps/Loading/Http/Paginators/SimpleWebsitePaginator.php, tests/Steps/Loading/Http/Paginators/SimpleWebsitePaginatorTest.php
Calling the `registerLoadedRequest()` method in the `SimpleWebsitePaginator` only with the request and not with the RespondedRequest when available, caused that most pre-built stop rules says paginating should be stopped, because they doe not receive a response to check.
=> Fix using SimpleWebsitePaginator with stop rules
