crwlrsoft/crawler

- CHANGELOG.md
- src/Crawler.php
- src/Result.php
- tests/CrawlerTest.php
So you don't need to manually traverse the Generator, if you don't need the results where you're calling the crawler.
Also refactor a little in the Crawler class.
> Add runAndTraverse method to Crawler

- src/Crawler.php
For more flexibility in child classes.
> Change all private methods to protected

- src/Io.php
This was so hard to do I cannot find a word for it in the dictionary :)
> Clean up logic of Io's constructor

- composer.json
> Improve Composer scripts

- CHANGELOG.md
- src/Loader/Http/Traits/CheckRobotsTxt.php
- src/Steps/Html/DomQuery.php
- tests/Pest.php
- tests/Steps/Html/CssSelectorTest.php
- tests/Steps/Html/XPathQueryTest.php
Add methods first(), last(), nth(n), even() and odd() methods to the DomQuery class to narrow the selected matches further.
> Add filter methods to DomQuery class

- src/HttpCrawler.php
- src/Loader/Http/Politeness/Throttler.php
- tests/Loader/Http/HttpLoaderPolitenessTest.php
- tests/Loader/Http/Politeness/ThrottlerTest.php
To between 1.0 and 2.0 of previous request and at least 0.25 seconds.
> Increase default throttling

- CHANGELOG.md
- src/Steps/Loading/Http.php
- src/Steps/Loading/Http/Paginate.php
- src/Steps/Loading/HttpCrawl.php
- tests/_Integration/Http/PublisherExampleTest.php
- tests/_Integration/Server.php
- tests/_Integration/_Server/Publisher/AuthorDetailPage.php
- tests/_Integration/_Server/Publisher/AuthorsListPage.php
- tests/_Integration/_Server/Publisher/BookDetailPage.php
The base `Http` step can now also be called with an array of URLs as a single input. Crawl and Paginate steps still require a single URL input.
> Base Http step also works with array of URLs

- CHANGELOG.md
- src/Steps/Json.php
- tests/Steps/JsonTest.php
Improve attempt to fix JSON strings having keys without quotes in the Json step.
> Improve fixing JSON having keys without quotes

- .github/workflows/ci.yml
@otsch Sorry for the per commit PR-s.
> Improve CI in four ways

- CHANGELOG.md
- src/Steps/Json.php
- tests/Steps/JsonTest.php
JSON step: another fix for JSON strings having keys without quotes with empty string value.
> Fix JSON keys with empty string value

- CHANGELOG.md
- src/Crawler.php
- tests/CrawlerTest.php
As a simple way to just run a crawler and dump all results, each as an array.
> Add Crawler::runAndDump()

- composer.json
- phpstan.neon
- phpunit.xml
- tests/Cache/FileCacheTest.php
- tests/CrawlerTest.php
- tests/Loader/AddLoadersToStepActionTest.php
- tests/Loader/Http/HttpLoaderPolitenessTest.php
- tests/Loader/Http/HttpLoaderTest.php
- tests/Loader/Http/Politeness/RobotsTxtHandlerTest.php
- tests/Logger/CliLoggerTest.php
- tests/Steps/DomTest.php
- tests/Steps/Loading/Http/Paginators/SimpleWebsitePaginatorTest.php
- tests/Steps/Refiners/AbstractRefinerTest.php
- tests/Steps/Refiners/String/AfterFirstTest.php
- tests/Steps/Refiners/String/AfterLastTest.php
- tests/Steps/Refiners/String/BeforeFirstTest.php
- tests/Steps/Refiners/String/BeforeLastTest.php
- tests/Steps/Refiners/String/BetweenFirstTest.php
- tests/Steps/Refiners/String/BetweenLastTest.php
- tests/Steps/Refiners/String/ReplaceTest.php
- tests/Steps/StepTest.php
- tests/_Integration/Http/PaginationTest.php
- tests/_Integration/Http/RedirectTest.php
- tests/_Integration/Http/TimeoutTest.php
And make a few improvements for phpstan.
> Upgrade to pest v2

- tests/Steps/Loading/HttpTest.php
Just that.
[_source_](https://github.com/szepeviktor/typos-on-you/actions/runs/5411081589)
> Fix typo in HttpTest

- .github/workflows/ci.yml
Also upgrade to use actions/checkout@v4.
> Run tests als in PHP 8.3 in CI

- CHANGELOG.md
- src/Loader/Http/HeadlessBrowserLoaderHelper.php
- tests/Loader/Http/HeadlessBrowserLoaderHelperTest.php
> Fix issue with setting chrome executable

- src/Steps/Loading/Http.php
As seen on TV
https://github.com/crwlrsoft/crawler/blob/a064aeb05d6dcea099cac245190103045efc7606/src/Cache/FileCache.php#L236
> Detect gzip encoding in Http

- src/Cache/FileCache.php
- src/Steps/Loading/Http.php
- src/Utils/Gzip.php
- tests/Utils/GzipTest.php
I found that gzip recognition, added by Viktor Szépe, was already used in another place in FileCache. So, I refactored to have a Gzip util class, handling encoding and decoding strings.
> Centralize gzip compression

- src/Loader/Http/Cookies/CookieJar.php
> Fix copy-pasta in CookieJar

- CHANGELOG.md
- src/Loader/Http/Cookies/CookieJar.php
- tests/Loader/Http/Cookies/CookieJarTest.php
Fixes issue when converting cookie objects received from the chrome-php library.
> Fix converting chrome-php cookie objects

- CHANGELOG.md
- LICENSE
- src/Loader/Http/HttpLoader.php
- src/Loader/Http/Messages/RespondedRequest.php
- tests/Loader/Http/HttpLoaderTest.php
`RespondedRequest::isServedFromCache()` to determine whether a response was served from cache or actually loaded.
> Add RespondedRequest::isServedFromCache()
